language: node_js
node_js:
  - 15
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  target_branch: gh_pages
  verbose: true
  on:
    branch: master